### ISSUE TITLE
【重要，请删除代码仓，谢谢】

### ISSUE THREAD

**Issue by lqwu** [lostsnow/keqing#67]
您好
      您github上有fork我的project代码，[C3-jzl](https://github.com/lostsnow/C3-jzl)，此代码涉及商业机密，已收律师函，请尽快删除。
      另外看这个仓库有几个fork记录，我无法查询详细信息，请你帮忙协助查询其他fork的人，联系方式发给我，由我联系删除。
      如有疑问，请邮件联系我 liu515740520@163.com，非常感谢！

**Comment by lostsnow** [comment]
https://github.com/ma7dy/C3-jzl/forks?include=active%2Cinactive&page=1&period=&sort_by=stargazer_counts

**Comment by lqwu** [comment]
非常感谢！
